### ISSUE TITLE
Замечания по lw6

### ISSUE THREAD

**Issue by lulldev** [JohnSmithW/LabWork6#1]
**Общие**

- верните папку src и конфиги валидаторов, настройте только validate-css пути исходных файлов
- по БЭМ множество недочетов

**Comment by lulldev** [comment]
**Task1**

- в БЭМ не применяются добавочные классы, превратите этот кот в модификатор
```css
.container-menu__item.active {
  color: black;
}
```

**Comment by lulldev** [comment]
**Task2**

- userCommentAppend(isUser) должна принимать сообщение параметром, а еще лучше если и имя добавится в параметры тоже
- данный код должен быть в JS
```html
 <form onsubmit="return false"
```
- слишком много вызовов appendChild
```js
      newComment.appendChild(userName);
      newComment.appendChild(userComment);
```
можно сделать короче через innerHTML
-

**Comment by lulldev** [comment]
**Task3**

- смешанные стили БЭМ именования
```css
.form__label_validation {
  color: rgb(255, 100, 100);
  margin-bottom: 0.5vmax;
}

.form-field__input {
  border: 0.1vmax solid rgba(0, 0, 0, 0.116);
  border-radius: 0.2vmax;
  outline: none;
  padding: 0.2vmax;
  font-size: 0.9vmax;
}
```

- в JS логике нужно изабавиться от привязке к индексам `formError[1]`, а сделать доступ к элементам формы по селекторам
